[build]
cmd = "go build -o ./tmp/main ./cmd/app/main.go"
bin = "tmp/main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
delay = 1000
stop_on_error = true

[log]
time = true